name: Build Custom OpenWrt with Zapret

on:
  workflow_dispatch: # Позволяет запускать сборку вручную кнопкой

env:
  OPENWRT_VERSION: "24.10.7"                     # Версия для скачивания самого Image Builder
  ZAPRET_REPO_VERSION: "24.10"                   # Версия для репозитория Запрета
  TARGET: "mediatek"                             # Твой процессор Mediatek
  SUBTARGET: "filogic"                           # Твое семейство чипов Filogic
  PROFILE: "cudy_wr3000p-v1"                     # Твой роутер Cudy WR3000P v1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Build Dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential gawk git texinfo libssl-dev xz-utils rsync wget unzip zstd

    - name: Download and Extract OpenWrt Image Builder
      run: |
        IB_URL="https://downloads.openwrt.org/releases/${{ env.OPENWRT_VERSION }}/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/openwrt-imagebuilder-${{ env.OPENWRT_VERSION }}-${{ env.TARGET }}-${{ env.SUBTARGET }}.Linux-x86_64.tar.zst"
        wget $IB_URL
        tar -xf *.tar.zst
        mv openwrt-imagebuilder-* ib

    - name: Add Custom Repositories (Remittor Zapret)
      run: |
        # Ищем ВСЕ файлы .conf в папке сборщика и намертво глушим проверку подписей цифровых ключей
        find ib/ -name "*.conf" -exec sed -i 's/option check_signature/# option check_signature/g' {} +
        
        # Добавляем пути к репозиториям Запрета
        echo "src/gz remittor_zapret_target https://raw.githubusercontent.com/remittor/opkg-repo/master/${{ env.ZAPRET_REPO_VERSION }}/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}" >> ib/repositories.conf
        echo "src/gz remittor_zapret_packages https://raw.githubusercontent.com/remittor/opkg-repo/master/${{ env.ZAPRET_REPO_VERSION }}/packages/aarch64_cortex-a53/zapret" >> ib/repositories.conf

    - name: Prepare Custom Files
      run: |
        if [ -d "files" ]; then
          mkdir -p ib/files
          cp -r files/* ib/files/
          chmod +x ib/files/opt/zapret2/init.d/zapret || true
          chmod +x ib/files/opt/zapret2/ipset/*.sh || true
        fi

    - name: Build Firmware Image
      run: |
        cd ib
        # Собираем систему. Запрет и интерфейс теперь зашьются без криков про безопасность
        make image PROFILE="${{ env.PROFILE }}" PACKAGES="luci luci-app-zapret zapret curl" FILES="files"

    - name: Upload Firmware Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: custom-openwrt-firmware
        path: ib/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/*-sysupgrade.bin
